name: Terraform por Ambiente

on:
  push:
    branches: [dev, pre, prd]
  pull_request:
    branches: [dev, pre, prd]

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      repo-path: ${{ steps.checkout.outputs.repo-path }}
    steps:
      - name: Checkout do código
        id: checkout
        uses: actions/checkout@v3

  terraform_init:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

  terraform_validate:
    runs-on: ubuntu-latest
    needs: terraform_init
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Validate
        run: terraform validate

  terraform_plan:
    runs-on: ubuntu-latest
    needs: terraform_validate
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Plan
        run: terraform plan -input=false

  terraform_apply:
    if: github.ref == 'refs/heads/pre' || github.ref == 'refs/heads/prd'
    runs-on: ubuntu-latest
    needs: terraform_plan
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
